=== AlanTrujilloRoldan/tecweb/practicas/p14/serviciovod.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT servicioVOD (pelicula*, programa*)>

<!ELEMENT pelicula (titulo, director, año)>
<!ATTLIST pelicula
    id CDATA #REQUIRED
    categoria CDATA #REQUIRED
>

<!ELEMENT programa (titulo, temporadas, episodios)>
<!ATTLIST programa
    id CDATA #REQUIRED
    categoria CDATA #REQUIRED
>

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT temporadas (#PCDATA)>
<!ELEMENT episodios (#PCDATA)>

=== AlanTrujilloRoldan/tecweb/practicas/p14/serviciovod2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE servicioVOD SYSTEM "serviciovod.dtd">
<servicioVOD>
    <pelicula id="001" categoria="Acción">
        <titulo>Rapidos y Furiosos 1</titulo>
        <director>Rob Cohen</director>
        <año>2001</año>
    </pelicula>
    <pelicula id="002" categoria="Drama">
        <titulo>Lo Imposible</titulo>
        <director>Juan Antonio Bayona</director>
        <año>2012</año>
    </pelicula>
    <programa id="003" categoria="Comedia">
        <titulo>The Office</titulo>
        <temporadas>9</temporadas>
        <episodios>201</episodios>
    </programa>
</servicioVOD>

=== AlanTrujilloRoldan/tecweb/practicas/p14/serviciovod3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE servicioVOD SYSTEM "serviciovod.dtd">
<servicioVOD>
    <pelicula id="001" categoria="Acción">
        <titulo>&lt;video id="11"&gt;&amp;lt;&lt;/video&gt;</titulo> <!-- Uso de entidades predefinidas -->
        <director>George Miller</director>
        <año>2015</año>
    </pelicula>
    <pelicula id="002" categoria="Drama">
        <titulo>Forrest Gump</titulo>
        <director>Robert Zemeckis</director>
        <año>1994</año>
    </pelicula>
    <programa id="P01" categoria="Comedia">
        <titulo><![CDATA[<video id="11">&lt;</video>]]></titulo> <!-- Uso de CDATA -->
        <temporadas>9</temporadas>
        <episodios>201</episodios>
    </programa>
</servicioVOD>
